# not considering 'license plate' and 'rectification border' labels from the dataset

LEVEL1 = {
    'road': 0,
    'parking': 1,
    'drivable fallback': 2,
    'sidewalk': 3,
    'non-drivable fallback': 4,
    'rail track': 5,
    'person': 6,
    'animal': 7,
    'rider': 8, 
    'motorcycle': 9,
    'bicycle': 10,
    'autorickshaw': 11,
    'car': 12,
    'truck': 13,
    'bus': 14,
    'caravan': 15,
    'trailer': 16,
    'vehicle fallback': 17,
    'curb': 18,
    'wall': 19,
    'fence': 20,
    'guard rail': 21,
    'billboard': 22,
    'traffic sign': 23,
    'traffic light': 24,
    'pole': 25,
    'polegroup': 26,
    'obs-str-bar-fallback': 27,
    'building': 28,
    'bridge': 29,
    'tunnel': 30,
    'vegetation': 31,
    'sky': 32,
    'fallback background': 33,
    'out of roi': 255,
}

LEVEL2 = {
    'road': 0,
    'parking': 1,
    'drivable fallback': 1,
    'sidewalk': 2,
    'non-drivable fallback': 3,
    'rail track': 3,
    'person': 4,
    'animal': 4,
    'rider': 5, 
    'motorcycle': 6,
    'bicycle': 7,
    'autorickshaw': 8,
    'car': 9,
    'truck': 10,
    'bus': 11,
    'caravan': 12,
    'trailer': 12,
    'vehicle fallback': 12,
    'curb': 13,
    'wall': 14,
    'fence': 15,
    'guard rail': 16,
    'billboard': 17,
    'traffic sign': 18,
    'traffic light': 19,
    'pole': 20,
    'polegroup': 20,
    'obs-str-bar-fallback': 21,
    'building': 22,
    'bridge': 23,
    'tunnel': 23,
    'vegetation': 24,
    'sky': 25,
    'fallback background': 25,
    'out of roi': 255,
}

LEVEL3 = {
    'road': 0,
    'parking': 1,
    'drivable fallback': 1,
    'sidewalk': 2,
    'non-drivable fallback': 3,
    'rail track': 3,
    'person': 4,
    'animal': 4,
    'rider': 5, 
    'motorcycle': 6,
    'bicycle': 6,
    'autorickshaw': 7,
    'car': 7,
    'truck': 8,
    'bus': 8,
    'caravan': 8,
    'trailer': 8,
    'vehicle fallback': 8,
    'curb': 9,
    'wall': 9,
    'fence': 10,
    'guard rail': 10,
    'billboard': 11,
    'traffic sign': 11,
    'traffic light': 11,
    'pole': 12,
    'polegroup': 12,
    'obs-str-bar-fallback': 12,
    'building': 13,
    'bridge': 13,
    'tunnel': 13,
    'vegetation': 14,
    'sky': 15,
    'fallback background': 15,
    'out of roi': 255,
}

LEVEL4 = {
    'road': 0,
    'parking': 0,
    'drivable fallback': 0,
    'sidewalk': 1,
    'non-drivable fallback': 1,
    'rail track': 1,
    'person': 2,
    'animal': 2,
    'rider': 2, 
    'motorcycle': 3,
    'bicycle': 3,
    'autorickshaw': 3,
    'car': 3,
    'truck': 3,
    'bus': 3,
    'caravan': 3,
    'trailer': 3,
    'vehicle fallback': 3,
    'curb': 4,
    'wall': 4,
    'fence': 4,
    'guard rail': 4,
    'billboard': 4,
    'traffic sign': 4,
    'traffic light': 4,
    'pole': 4,
    'polegroup': 4,
    'obs-str-bar-fallback': 4,
    'building': 5,
    'bridge': 5,
    'tunnel': 5,
    'vegetation': 5,
    'sky': 6,
    'fallback background': 6,
    'out of roi': 255,
}

LEVEL4_text = {
    0: 'drivable',
    1: 'non-drivable',
    2: 'living-things',
    3: 'vehicles',
    4: 'road-side objects',
    5: 'far objects',
    6: 'sky',
    255: 'not for training',
}